fail_fast: false
repos:
  - hooks:
      - id: check-yaml
      - exclude: .vscode
        id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
  - hooks:
      - exclude_types:
          - javascript
          - json
        id: clang-format
    repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.2
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: v0.11.0
    hooks:
      - id: yamlfmt
