name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {name: Windows VS2019, os: windows-2019}
          - {name: Windows VS2022, os: windows-2022}
          - {name: Linux GCC, os: ubuntu-latest}
          - {name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++}
          - {name: macOS, os: macos-latest}
        config:
          - {name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE}
          - {name: Static, flags: -DBUILD_SHARED_LIBS=FALSE}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev freeglut3-dev
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} ${{matrix.config.flags}}
      - name: Build
        shell: bash
        run: cmake --build build --config Release
      - name: Install
        shell: bash
        run: cmake --install build --config Release
