name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {name: Windows VS2019, os: windows-2019}
          - {name: Windows VS2022, os: windows-2022}
          - {name: Linux GCC, os: ubuntu-latest}
          - {name: Linux Clang, os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++}
          - {name: macOS, os: macos-13}
        config:
          - {name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE}
          - {name: Static, flags: -DBUILD_SHARED_LIBS=FALSE}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev freeglut3-dev libxinerama-dev libxi-dev libwayland-dev libxkbcommon-dev xorg-dev
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Configure
        shell: bash
        run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install ${{matrix.platform.flags}} ${{matrix.config.flags}}
      - name: Build
        shell: bash
        run: cmake --build build --config Release
      - name: Install
        shell: bash
        run: cmake --install build --config Release
