name: Documentation
on:
  push:
    tags:
      - "*"
    branches: [main, master]
permissions:
  contents: read
jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      - name: Install Docs
        run: |
          sudo apt-get install doxygen
          pip install -r requirements.txt  --require-hashes
      - name: prepare
        run: |
          make prepare
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target docs -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@526a34f794dfdf7edd6a4ac94321b1e7945910c0 # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./docs/html
